version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    command: npm start
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/carbonlens
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    command: sh -c "npm run build && npm install -g serve && serve -s dist"

  mongo:
    image: mongo:6
    container_name: mongo_prod
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-prod:/data/db

volumes:
  mongo-data-prod:
